//This file is autogenerated for
//    CancellationSignal.class
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_CANCELLATIONSIGNAL_CALLBACK_DEC_HH
#define ELASTOS_CANCELLATIONSIGNAL_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_CancellationSignal_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace AndroidWebview {

struct ElaCancellationSignalCallback
{
    Boolean (*elastos_CancellationSignal_isCanceled)(IInterface* obj);
    void (*elastos_CancellationSignal_throwIfCanceled)(IInterface* obj);
    void (*elastos_CancellationSignal_cancel)(IInterface* obj);
    void (*elastos_CancellationSignal_setOnCancelListener)(IInterface* obj, IInterface* p0);
    AutoPtr<IInterface> (*elastos_CancellationSignal_Constructor)();
};

void* CancellationSignal::ElaCancellationSignalCallback_Init()
{
    static ElaCancellationSignalCallback sElaCancellationSignalCallback;

    sElaCancellationSignalCallback.elastos_CancellationSignal_isCanceled = &CancellationSignal::IsCanceled;
    sElaCancellationSignalCallback.elastos_CancellationSignal_throwIfCanceled = &CancellationSignal::ThrowIfCanceled;
    sElaCancellationSignalCallback.elastos_CancellationSignal_cancel = &CancellationSignal::Cancel;
    sElaCancellationSignalCallback.elastos_CancellationSignal_setOnCancelListener = &CancellationSignal::SetOnCancelListener;
    sElaCancellationSignalCallback.elastos_CancellationSignal_Constructor = &CancellationSignal::Constructor;

    Elastos_CancellationSignal_InitCallback((Handle32)&sElaCancellationSignalCallback);
    return &sElaCancellationSignalCallback;
}

static void* sPElaCancellationSignalCallback = CancellationSignal::ElaCancellationSignalCallback_Init();

} // namespace AndroidWebview
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_CANCELLATIONSIGNAL_CALLBACK_DEC_HH
