//This file is autogenerated for
//    DateTimeChooserAndroid.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_DATETIMECHOOSERANDROID_CALLBACK_DEC_HH
#define ELASTOS_DATETIMECHOOSERANDROID_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_DateTimeChooserAndroid_nativeReplaceDateTime(IInterface* caller,Handle32 nativeDateTimeChooserAndroid,Double dialogValue);
    extern void Elastos_DateTimeChooserAndroid_nativeCancelDialog(IInterface* caller,Handle32 nativeDateTimeChooserAndroid);
    extern void Elastos_DateTimeChooserAndroid_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Content {
namespace Browser {
namespace Input {

struct ElaDateTimeChooserAndroidCallback
{
    AutoPtr<IInterface> (*elastos_DateTimeChooserAndroid_createDateTimeChooser)(IInterface* contentViewCore, Int64 nativeDateTimeChooserAndroid, Int32 dialogType, Double dialogValue, Double min, Double max, Double step, ArrayOf<IInterface*>* suggestions);
    AutoPtr<ArrayOf<IInterface*> > (*elastos_DateTimeChooserAndroid_createSuggestionsArray)(Int32 size);
    void (*elastos_DateTimeChooserAndroid_setDateTimeSuggestionAt)(ArrayOf<IInterface*>* array, Int32 index, Double value, const String& localizedValue, const String& label);
    void (*elastos_DateTimeChooserAndroid_initializeDateInputTypes)(Int32 textInputTypeDate, Int32 textInputTypeDateTime, Int32 textInputTypeDateTimeLocal, Int32 textInputTypeMonth, Int32 textInputTypeTime, Int32 textInputTypeWeek);
};

void* DateTimeChooserAndroid::ElaDateTimeChooserAndroidCallback_Init()
{
    static ElaDateTimeChooserAndroidCallback sElaDateTimeChooserAndroidCallback;

    sElaDateTimeChooserAndroidCallback.elastos_DateTimeChooserAndroid_createDateTimeChooser = &DateTimeChooserAndroid::CreateDateTimeChooser;
    sElaDateTimeChooserAndroidCallback.elastos_DateTimeChooserAndroid_createSuggestionsArray = &DateTimeChooserAndroid::CreateSuggestionsArray;
    sElaDateTimeChooserAndroidCallback.elastos_DateTimeChooserAndroid_setDateTimeSuggestionAt = &DateTimeChooserAndroid::SetDateTimeSuggestionAt;
    sElaDateTimeChooserAndroidCallback.elastos_DateTimeChooserAndroid_initializeDateInputTypes = &DateTimeChooserAndroid::InitializeDateInputTypes;

    Elastos_DateTimeChooserAndroid_InitCallback((Handle32)&sElaDateTimeChooserAndroidCallback);
    return &sElaDateTimeChooserAndroidCallback;
}

static void* sPElaDateTimeChooserAndroidCallback = DateTimeChooserAndroid::ElaDateTimeChooserAndroidCallback_Init();

} // namespace Input
} // namespace Browser
} // namespace Content
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_DATETIMECHOOSERANDROID_CALLBACK_DEC_HH
