//This file is autogenerated for
//    MotionEvent.class
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_MOTIONEVENT_CALLBACK_DEC_HH
#define ELASTOS_MOTIONEVENT_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_MotionEvent_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Content {
namespace Browser {

struct ElaMotionEventCallback
{
    void (*elastos_MotionEvent_finalize)(IInterface* obj);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_I_LAVMEPP_LAVMEPC_I_I_F_F_I_I_I_I)(Int64 p0, Int64 p1, Int32 p2, Int32 p3, ArrayOf<AutoPtr<IInterface> >* p4, ArrayOf<AutoPtr<IInterface> >* p5, Int32 p6, Int32 p7, Float p8, Float p9, Int32 p10, Int32 p11, Int32 p12, Int32 p13);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_I_AI_LAVMEPC_I_F_F_I_I_I_I)(Int64 p0, Int64 p1, Int32 p2, Int32 p3, ArrayOf<Int32>* p4, ArrayOf<AutoPtr<IInterface> >* p5, Int32 p6, Float p7, Float p8, Int32 p9, Int32 p10, Int32 p11, Int32 p12);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_F_F_F_F_I_F_F_I_I)(Int64 p0, Int64 p1, Int32 p2, Float p3, Float p4, Float p5, Float p6, Int32 p7, Float p8, Float p9, Int32 p10, Int32 p11);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_I_F_F_F_F_I_F_F_I_I)(Int64 p0, Int64 p1, Int32 p2, Int32 p3, Float p4, Float p5, Float p6, Float p7, Int32 p8, Float p9, Float p10, Int32 p11, Int32 p12);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_J_J_I_F_F_I)(Int64 p0, Int64 p1, Int32 p2, Float p3, Float p4, Int32 p5);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainAVME_AVME)(IInterface* p0);
    AutoPtr<IInterface> (*elastos_MotionEvent_obtainNoHistory)(IInterface* p0);
    void (*elastos_MotionEvent_recycle)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getDeviceId)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getSource)(IInterface* obj);
    void (*elastos_MotionEvent_setSource)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_getAction)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getActionMasked)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getActionIndex)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getFlags)(IInterface* obj);
    Int64 (*elastos_MotionEvent_getDownTime)(IInterface* obj);
    Int64 (*elastos_MotionEvent_getEventTime)(IInterface* obj);
    Float (*elastos_MotionEvent_getXF)(IInterface* obj);
    Float (*elastos_MotionEvent_getYF)(IInterface* obj);
    Float (*elastos_MotionEvent_getPressureF)(IInterface* obj);
    Float (*elastos_MotionEvent_getSizeF)(IInterface* obj);
    Float (*elastos_MotionEvent_getTouchMajorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getTouchMinorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getToolMajorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getToolMinorF)(IInterface* obj);
    Float (*elastos_MotionEvent_getOrientationF)(IInterface* obj);
    Float (*elastos_MotionEvent_getAxisValueF_I)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_getPointerCount)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getPointerId)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_getToolType)(IInterface* obj, Int32 p0);
    Int32 (*elastos_MotionEvent_findPointerIndex)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getXF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getYF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getPressureF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getSizeF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getTouchMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getTouchMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getToolMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getToolMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getOrientationF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getAxisValueF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    void (*elastos_MotionEvent_getPointerCoords)(IInterface* obj, Int32 p0, IInterface* p1);
    void (*elastos_MotionEvent_getPointerProperties)(IInterface* obj, Int32 p0, IInterface* p1);
    Int32 (*elastos_MotionEvent_getMetaState)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getButtonState)(IInterface* obj);
    Float (*elastos_MotionEvent_getRawX)(IInterface* obj);
    Float (*elastos_MotionEvent_getRawY)(IInterface* obj);
    Float (*elastos_MotionEvent_getXPrecision)(IInterface* obj);
    Float (*elastos_MotionEvent_getYPrecision)(IInterface* obj);
    Int32 (*elastos_MotionEvent_getHistorySize)(IInterface* obj);
    Int64 (*elastos_MotionEvent_getHistoricalEventTime)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalXF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalYF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalPressureF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalSizeF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalTouchMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalTouchMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalToolMajorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalToolMinorF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalOrientationF_I)(IInterface* obj, Int32 p0);
    Float (*elastos_MotionEvent_getHistoricalAxisValueF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalXF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalYF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalPressureF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalSizeF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalTouchMajorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalTouchMinorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalToolMajorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalToolMinorF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalOrientationF_I_I)(IInterface* obj, Int32 p0, Int32 p1);
    Float (*elastos_MotionEvent_getHistoricalAxisValueF_I_I_I)(IInterface* obj, Int32 p0, Int32 p1, Int32 p2);
    void (*elastos_MotionEvent_getHistoricalPointerCoords)(IInterface* obj, Int32 p0, Int32 p1, IInterface* p2);
    Int32 (*elastos_MotionEvent_getEdgeFlags)(IInterface* obj);
    void (*elastos_MotionEvent_setEdgeFlags)(IInterface* obj, Int32 p0);
    void (*elastos_MotionEvent_setAction)(IInterface* obj, Int32 p0);
    void (*elastos_MotionEvent_offsetLocation)(IInterface* obj, Float p0, Float p1);
    void (*elastos_MotionEvent_setLocation)(IInterface* obj, Float p0, Float p1);
    void (*elastos_MotionEvent_transform)(IInterface* obj, IInterface* p0);
    void (*elastos_MotionEvent_addBatchV_J_F_F_F_F_I)(IInterface* obj, Int64 p0, Float p1, Float p2, Float p3, Float p4, Int32 p5);
    void (*elastos_MotionEvent_addBatchV_J_LAVMEPC_I)(IInterface* obj, Int64 p0, ArrayOf<AutoPtr<IInterface> >* p1, Int32 p2);
    String (*elastos_MotionEvent_toString)(IInterface* obj);
    String (*elastos_MotionEvent_axisToString)(Int32 p0);
    Int32 (*elastos_MotionEvent_axisFromString)(const String& p0);
    void (*elastos_MotionEvent_writeToParcel)(IInterface* obj, IInterface* p0, Int32 p1);
};

void* MotionEvent::ElaMotionEventCallback_Init()
{
    static ElaMotionEventCallback sElaMotionEventCallback;

    sElaMotionEventCallback.elastos_MotionEvent_finalize = &MotionEvent::Finalize;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_I_LAVMEPP_LAVMEPC_I_I_F_F_I_I_I_I = &MotionEvent::MotionEvent_obtainAVME_J_J_I_I_LAVMEPP_LAVMEPC_I_I_F_F_I_I_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_I_AI_LAVMEPC_I_F_F_I_I_I_I = &MotionEvent::MotionEvent_obtainAVME_J_J_I_I_AI_LAVMEPC_I_F_F_I_I_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_F_F_F_F_I_F_F_I_I = &MotionEvent::MotionEvent_obtainAVME_J_J_I_F_F_F_F_I_F_F_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_I_F_F_F_F_I_F_F_I_I = &MotionEvent::MotionEvent_obtainAVME_J_J_I_I_F_F_F_F_I_F_F_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_J_J_I_F_F_I = &MotionEvent::MotionEvent_obtainAVME_J_J_I_F_F::I;
    sElaMotionEventCallback.elastos_MotionEvent_obtainAVME_AVME = &MotionEvent::MotionEvent_obtainAVME::AVME;
    sElaMotionEventCallback.elastos_MotionEvent_obtainNoHistory = &MotionEvent::ObtainNoHistory;
    sElaMotionEventCallback.elastos_MotionEvent_recycle = &MotionEvent::Recycle;
    sElaMotionEventCallback.elastos_MotionEvent_getDeviceId = &MotionEvent::GetDeviceId;
    sElaMotionEventCallback.elastos_MotionEvent_getSource = &MotionEvent::GetSource;
    sElaMotionEventCallback.elastos_MotionEvent_setSource = &MotionEvent::SetSource;
    sElaMotionEventCallback.elastos_MotionEvent_getAction = &MotionEvent::GetAction;
    sElaMotionEventCallback.elastos_MotionEvent_getActionMasked = &MotionEvent::GetActionMasked;
    sElaMotionEventCallback.elastos_MotionEvent_getActionIndex = &MotionEvent::GetActionIndex;
    sElaMotionEventCallback.elastos_MotionEvent_getFlags = &MotionEvent::GetFlags;
    sElaMotionEventCallback.elastos_MotionEvent_getDownTime = &MotionEvent::GetDownTime;
    sElaMotionEventCallback.elastos_MotionEvent_getEventTime = &MotionEvent::GetEventTime;
    sElaMotionEventCallback.elastos_MotionEvent_getXF = &MotionEvent::GetXF;
    sElaMotionEventCallback.elastos_MotionEvent_getYF = &MotionEvent::GetYF;
    sElaMotionEventCallback.elastos_MotionEvent_getPressureF = &MotionEvent::GetPressureF;
    sElaMotionEventCallback.elastos_MotionEvent_getSizeF = &MotionEvent::GetSizeF;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMajorF = &MotionEvent::GetTouchMajorF;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMinorF = &MotionEvent::GetTouchMinorF;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMajorF = &MotionEvent::GetToolMajorF;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMinorF = &MotionEvent::GetToolMinorF;
    sElaMotionEventCallback.elastos_MotionEvent_getOrientationF = &MotionEvent::GetOrientationF;
    sElaMotionEventCallback.elastos_MotionEvent_getAxisValueF_I = &MotionEvent::MotionEvent_getAxisValueF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerCount = &MotionEvent::GetPointerCount;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerId = &MotionEvent::GetPointerId;
    sElaMotionEventCallback.elastos_MotionEvent_getToolType = &MotionEvent::GetToolType;
    sElaMotionEventCallback.elastos_MotionEvent_findPointerIndex = &MotionEvent::FindPointerIndex;
    sElaMotionEventCallback.elastos_MotionEvent_getXF_I = &MotionEvent::MotionEvent_getXF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getYF_I = &MotionEvent::MotionEvent_getYF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getPressureF_I = &MotionEvent::MotionEvent_getPressureF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getSizeF_I = &MotionEvent::MotionEvent_getSizeF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMajorF_I = &MotionEvent::MotionEvent_getTouchMajorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getTouchMinorF_I = &MotionEvent::MotionEvent_getTouchMinorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMajorF_I = &MotionEvent::MotionEvent_getToolMajorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getToolMinorF_I = &MotionEvent::MotionEvent_getToolMinorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getOrientationF_I = &MotionEvent::MotionEvent_getOrientationF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getAxisValueF_I_I = &MotionEvent::MotionEvent_getAxisValueF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerCoords = &MotionEvent::GetPointerCoords;
    sElaMotionEventCallback.elastos_MotionEvent_getPointerProperties = &MotionEvent::GetPointerProperties;
    sElaMotionEventCallback.elastos_MotionEvent_getMetaState = &MotionEvent::GetMetaState;
    sElaMotionEventCallback.elastos_MotionEvent_getButtonState = &MotionEvent::GetButtonState;
    sElaMotionEventCallback.elastos_MotionEvent_getRawX = &MotionEvent::GetRawX;
    sElaMotionEventCallback.elastos_MotionEvent_getRawY = &MotionEvent::GetRawY;
    sElaMotionEventCallback.elastos_MotionEvent_getXPrecision = &MotionEvent::GetXPrecision;
    sElaMotionEventCallback.elastos_MotionEvent_getYPrecision = &MotionEvent::GetYPrecision;
    sElaMotionEventCallback.elastos_MotionEvent_getHistorySize = &MotionEvent::GetHistorySize;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalEventTime = &MotionEvent::GetHistoricalEventTime;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalXF_I = &MotionEvent::MotionEvent_getHistoricalXF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalYF_I = &MotionEvent::MotionEvent_getHistoricalYF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalPressureF_I = &MotionEvent::MotionEvent_getHistoricalPressureF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalSizeF_I = &MotionEvent::MotionEvent_getHistoricalSizeF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMajorF_I = &MotionEvent::MotionEvent_getHistoricalTouchMajorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMinorF_I = &MotionEvent::MotionEvent_getHistoricalTouchMinorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMajorF_I = &MotionEvent::MotionEvent_getHistoricalToolMajorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMinorF_I = &MotionEvent::MotionEvent_getHistoricalToolMinorF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalOrientationF_I = &MotionEvent::MotionEvent_getHistoricalOrientationF::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalAxisValueF_I_I = &MotionEvent::MotionEvent_getHistoricalAxisValueF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalXF_I_I = &MotionEvent::MotionEvent_getHistoricalXF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalYF_I_I = &MotionEvent::MotionEvent_getHistoricalYF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalPressureF_I_I = &MotionEvent::MotionEvent_getHistoricalPressureF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalSizeF_I_I = &MotionEvent::MotionEvent_getHistoricalSizeF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMajorF_I_I = &MotionEvent::MotionEvent_getHistoricalTouchMajorF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalTouchMinorF_I_I = &MotionEvent::MotionEvent_getHistoricalTouchMinorF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMajorF_I_I = &MotionEvent::MotionEvent_getHistoricalToolMajorF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalToolMinorF_I_I = &MotionEvent::MotionEvent_getHistoricalToolMinorF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalOrientationF_I_I = &MotionEvent::MotionEvent_getHistoricalOrientationF_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalAxisValueF_I_I_I = &MotionEvent::MotionEvent_getHistoricalAxisValueF_I_I::I;
    sElaMotionEventCallback.elastos_MotionEvent_getHistoricalPointerCoords = &MotionEvent::GetHistoricalPointerCoords;
    sElaMotionEventCallback.elastos_MotionEvent_getEdgeFlags = &MotionEvent::GetEdgeFlags;
    sElaMotionEventCallback.elastos_MotionEvent_setEdgeFlags = &MotionEvent::SetEdgeFlags;
    sElaMotionEventCallback.elastos_MotionEvent_setAction = &MotionEvent::SetAction;
    sElaMotionEventCallback.elastos_MotionEvent_offsetLocation = &MotionEvent::OffsetLocation;
    sElaMotionEventCallback.elastos_MotionEvent_setLocation = &MotionEvent::SetLocation;
    sElaMotionEventCallback.elastos_MotionEvent_transform = &MotionEvent::Transform;
    sElaMotionEventCallback.elastos_MotionEvent_addBatchV_J_F_F_F_F_I = &MotionEvent::MotionEvent_addBatchV_J_F_F_F_F::I;
    sElaMotionEventCallback.elastos_MotionEvent_addBatchV_J_LAVMEPC_I = &MotionEvent::MotionEvent_addBatchV_J_LAVMEPC::I;
    sElaMotionEventCallback.elastos_MotionEvent_toString = &MotionEvent::ToString;
    sElaMotionEventCallback.elastos_MotionEvent_axisToString = &MotionEvent::AxisToString;
    sElaMotionEventCallback.elastos_MotionEvent_axisFromString = &MotionEvent::AxisFromString;
    sElaMotionEventCallback.elastos_MotionEvent_writeToParcel = &MotionEvent::WriteToParcel;

    Elastos_MotionEvent_InitCallback((Handle32)&sElaMotionEventCallback);
    return &sElaMotionEventCallback;
}

static void* sPElaMotionEventCallback = MotionEvent::ElaMotionEventCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_MOTIONEVENT_CALLBACK_DEC_HH
