//This file is autogenerated for
//    TracingControllerAndroid.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_TRACINGCONTROLLERANDROID_CALLBACK_DEC_HH
#define ELASTOS_TRACINGCONTROLLERANDROID_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern Int64 Elastos_TracingControllerAndroid_nativeInit(IInterface* caller);
    extern String Elastos_TracingControllerAndroid_nativeGetDefaultCategories(IInterface* caller);
    extern void Elastos_TracingControllerAndroid_nativeDestroy(IInterface* caller,Handle32 nativeTracingControllerAndroid);
    extern Boolean Elastos_TracingControllerAndroid_nativeStartTracing(IInterface* caller,Handle32 nativeTracingControllerAndroid,const String& categories,Boolean recordContinuously);
    extern void Elastos_TracingControllerAndroid_nativeStopTracing(IInterface* caller,Handle32 nativeTracingControllerAndroid,const String& filename);
    extern Boolean Elastos_TracingControllerAndroid_nativeGetKnownCategoryGroupsAsync(IInterface* caller,Handle32 nativeTracingControllerAndroid);
    extern void Elastos_TracingControllerAndroid_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Content {
namespace Browser {

struct ElaTracingControllerAndroidCallback
{
    String (*elastos_TracingControllerAndroid_generateTracingFilePath)();
    void (*elastos_TracingControllerAndroid_onTracingStopped)(IInterface* obj);
};

void* TracingControllerAndroid::ElaTracingControllerAndroidCallback_Init()
{
    static ElaTracingControllerAndroidCallback sElaTracingControllerAndroidCallback;

    sElaTracingControllerAndroidCallback.elastos_TracingControllerAndroid_generateTracingFilePath = &TracingControllerAndroid::GenerateTracingFilePath;
    sElaTracingControllerAndroidCallback.elastos_TracingControllerAndroid_onTracingStopped = &TracingControllerAndroid::OnTracingStopped;

    Elastos_TracingControllerAndroid_InitCallback((Handle32)&sElaTracingControllerAndroidCallback);
    return &sElaTracingControllerAndroidCallback;
}

static void* sPElaTracingControllerAndroidCallback = TracingControllerAndroid::ElaTracingControllerAndroidCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_TRACINGCONTROLLERANDROID_CALLBACK_DEC_HH
