//This file is autogenerated for
//    WebContentsObserverAndroid.java
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_WEBCONTENTSOBSERVERANDROID_CALLBACK_DEC_HH
#define ELASTOS_WEBCONTENTSOBSERVERANDROID_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern Int64 Elastos_WebContentsObserverAndroid_nativeInit(IInterface* caller,IInterface* webContents);
    extern void Elastos_WebContentsObserverAndroid_nativeDestroy(IInterface* caller,Handle32 nativeWebContentsObserverAndroid);
    extern void Elastos_WebContentsObserverAndroid_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif


namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Content {
namespace Browser {

struct ElaWebContentsObserverAndroidCallback
{
    void (*elastos_WebContentsObserverAndroid_renderProcessGone)(IInterface* obj, Boolean wasOomProtected);
    void (*elastos_WebContentsObserverAndroid_didStartLoading)(IInterface* obj, const String& url);
    void (*elastos_WebContentsObserverAndroid_didStopLoading)(IInterface* obj, const String& url);
    void (*elastos_WebContentsObserverAndroid_didFailLoad)(IInterface* obj, Boolean isProvisionalLoad, Boolean isMainFrame, Int32 errorCode, const String& description, const String& failingUrl);
    void (*elastos_WebContentsObserverAndroid_didNavigateMainFrame)(IInterface* obj, const String& url, const String& baseUrl, Boolean isNavigationToDifferentPage, Boolean isFragmentNavigation);
    void (*elastos_WebContentsObserverAndroid_didFirstVisuallyNonEmptyPaint)(IInterface* obj);
    void (*elastos_WebContentsObserverAndroid_didNavigateAnyFrame)(IInterface* obj, const String& url, const String& baseUrl, Boolean isReload);
    void (*elastos_WebContentsObserverAndroid_didStartProvisionalLoadForFrame)(IInterface* obj, Int64 frameId, Int64 parentFrameId, Boolean isMainFrame, const String& validatedUrl, Boolean isErrorPage, Boolean isIframeSrcdoc);
    void (*elastos_WebContentsObserverAndroid_didCommitProvisionalLoadForFrame)(IInterface* obj, Int64 frameId, Boolean isMainFrame, const String& url, Int32 transitionType);
    void (*elastos_WebContentsObserverAndroid_didFinishLoad)(IInterface* obj, Int64 frameId, const String& validatedUrl, Boolean isMainFrame);
    void (*elastos_WebContentsObserverAndroid_documentLoadedInFrame)(IInterface* obj, Int64 frameId);
    void (*elastos_WebContentsObserverAndroid_navigationEntryCommitted)(IInterface* obj);
    void (*elastos_WebContentsObserverAndroid_didAttachInterstitialPage)(IInterface* obj);
    void (*elastos_WebContentsObserverAndroid_didDetachInterstitialPage)(IInterface* obj);
    void (*elastos_WebContentsObserverAndroid_didChangeThemeColor)(IInterface* obj, Int32 color);
    void (*elastos_WebContentsObserverAndroid_detachFromWebContents)(IInterface* obj);
};

void* WebContentsObserverAndroid::ElaWebContentsObserverAndroidCallback_Init()
{
    static ElaWebContentsObserverAndroidCallback sElaWebContentsObserverAndroidCallback;

    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_renderProcessGone = &WebContentsObserverAndroid::RenderProcessGone;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didStartLoading = &WebContentsObserverAndroid::DidStartLoading;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didStopLoading = &WebContentsObserverAndroid::DidStopLoading;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didFailLoad = &WebContentsObserverAndroid::DidFailLoad;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didNavigateMainFrame = &WebContentsObserverAndroid::DidNavigateMainFrame;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didFirstVisuallyNonEmptyPaint = &WebContentsObserverAndroid::DidFirstVisuallyNonEmptyPaint;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didNavigateAnyFrame = &WebContentsObserverAndroid::DidNavigateAnyFrame;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didStartProvisionalLoadForFrame = &WebContentsObserverAndroid::DidStartProvisionalLoadForFrame;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didCommitProvisionalLoadForFrame = &WebContentsObserverAndroid::DidCommitProvisionalLoadForFrame;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didFinishLoad = &WebContentsObserverAndroid::DidFinishLoad;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_documentLoadedInFrame = &WebContentsObserverAndroid::DocumentLoadedInFrame;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_navigationEntryCommitted = &WebContentsObserverAndroid::NavigationEntryCommitted;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didAttachInterstitialPage = &WebContentsObserverAndroid::DidAttachInterstitialPage;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didDetachInterstitialPage = &WebContentsObserverAndroid::DidDetachInterstitialPage;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_didChangeThemeColor = &WebContentsObserverAndroid::DidChangeThemeColor;
    sElaWebContentsObserverAndroidCallback.elastos_WebContentsObserverAndroid_detachFromWebContents = &WebContentsObserverAndroid::DetachFromWebContents;

    Elastos_WebContentsObserverAndroid_InitCallback((Handle32)&sElaWebContentsObserverAndroidCallback);
    return &sElaWebContentsObserverAndroidCallback;
}

static void* sPElaWebContentsObserverAndroidCallback = WebContentsObserverAndroid::ElaWebContentsObserverAndroidCallback_Init();

} // namespace Browser
} // namespace Content
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_WEBCONTENTSOBSERVERANDROID_CALLBACK_DEC_HH
