//This file is autogenerated for
//    Surface.class
//put this file at the end of the include list
//so the type definition used in this file will be found
#ifndef ELASTOS_SURFACE_CALLBACK_DEC_HH
#define ELASTOS_SURFACE_CALLBACK_DEC_HH


#ifdef __cplusplus
extern "C"
{
#endif
    extern void Elastos_Surface_InitCallback(Handle32 cb);
#ifdef __cplusplus
}
#endif

namespace Elastos {
namespace Droid {
namespace Webkit {
namespace Ui {

struct ElaSurfaceCallback
{
    void (*elastos_Surface_finalize)(IInterface* obj);
    void (*elastos_Surface_release)(IInterface* obj);
    Boolean (*elastos_Surface_isValid)(IInterface* obj);
    AutoPtr<IInterface> (*elastos_Surface_lockCanvas)(IInterface* obj, IInterface* p0);
    void (*elastos_Surface_unlockCanvasAndPost)(IInterface* obj, IInterface* p0);
    void (*elastos_Surface_unlockCanvas)(IInterface* obj, IInterface* p0);
    Int32 (*elastos_Surface_describeContents)(IInterface* obj);
    void (*elastos_Surface_readFromParcel)(IInterface* obj, IInterface* p0);
    void (*elastos_Surface_writeToParcel)(IInterface* obj, IInterface* p0, Int32 p1);
    String (*elastos_Surface_toString)(IInterface* obj);
    AutoPtr<IInterface> (*elastos_Surface_Constructor)(IInterface* p0);
};

void* Surface::ElaSurfaceCallback_Init()
{
    static ElaSurfaceCallback sElaSurfaceCallback;

    sElaSurfaceCallback.elastos_Surface_finalize = &Surface::Finalize;
    sElaSurfaceCallback.elastos_Surface_release = &Surface::ReleaseResource;
    sElaSurfaceCallback.elastos_Surface_isValid = &Surface::IsValid;
    sElaSurfaceCallback.elastos_Surface_lockCanvas = &Surface::LockCanvas;
    sElaSurfaceCallback.elastos_Surface_unlockCanvasAndPost = &Surface::UnlockCanvasAndPost;
    sElaSurfaceCallback.elastos_Surface_unlockCanvas = &Surface::UnlockCanvas;
    sElaSurfaceCallback.elastos_Surface_describeContents = &Surface::DescribeContents;
    sElaSurfaceCallback.elastos_Surface_readFromParcel = &Surface::ReadFromParcel;
    sElaSurfaceCallback.elastos_Surface_writeToParcel = &Surface::WriteToParcel;
    sElaSurfaceCallback.elastos_Surface_toString = &Surface::ToString;
    sElaSurfaceCallback.elastos_Surface_Constructor = &Surface::Constructor;

    Elastos_Surface_InitCallback((Handle32)&sElaSurfaceCallback);
    return &sElaSurfaceCallback;
}

static void* sPElaSurfaceCallback = Surface::ElaSurfaceCallback_Init();

} // namespace Ui
} // namespace Webkit
} // namespace Droid
} // namespace Elastos

#endif //ELASTOS_SURFACE_CALLBACK_DEC_HH
